# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Correlationc <- function(coordsx, coordsy, theta, covar, same) {
    .Call(`_spiox_Correlationc`, coordsx, coordsy, theta, covar, same)
}

daggp_build <- function(coords, dag, phi, sigmasq, nu, tausq, matern = FALSE, num_threads = 1L) {
    .Call(`_spiox_daggp_build`, coords, dag, phi, sigmasq, nu, tausq, matern, num_threads)
}

dl_update_variances <- function(theta, a, b) {
    .Call(`_spiox_dl_update_variances`, theta, a, b)
}

iox <- function(x, y, i, j, S, theta, matern = TRUE, diag_only = FALSE, at_limit = FALSE) {
    .Call(`_spiox_iox`, x, y, i, j, S, theta, matern, diag_only, at_limit)
}

sfact <- function(dag, S, theta, matern = TRUE, n_threads = 1L) {
    .Call(`_spiox_sfact`, dag, S, theta, matern, n_threads)
}

rvec <- function(x, i, S, theta, matern = TRUE) {
    .Call(`_spiox_rvec`, x, i, S, theta, matern)
}

make_ix <- function(q, n) {
    .Call(`_spiox_make_ix`, q, n)
}

iox_mat <- function(x, y, S, theta, matern = TRUE, D_only = FALSE) {
    .Call(`_spiox_iox_mat`, x, y, S, theta, matern, D_only)
}

make_candidates <- function(w, indsort, col, rho) {
    .Call(`_spiox_make_candidates`, w, indsort, col, rho)
}

neighbor_search_testset <- function(wtrain, wtest, rho) {
    .Call(`_spiox_neighbor_search_testset`, wtrain, wtest, rho)
}

run_spf_model <- function(Y, n_factors, delta_gamma_shape, delta_gamma_rate, dl_dirichlet_a, Lambda_start, Delta_start, mcmc = 1000L, print_every = 1000L, seq_lambda = FALSE) {
    .Call(`_spiox_run_spf_model`, Y, n_factors, delta_gamma_shape, delta_gamma_rate, dl_dirichlet_a, Lambda_start, Delta_start, mcmc, print_every, seq_lambda)
}

spiox_wishart <- function(Y, X, coords, custom_dag, theta_opts, Sigma_start, mvreg_B_start, mcmc = 1000L, print_every = 100L, sample_iwish = TRUE, sample_mvr = TRUE, sample_theta_gibbs = TRUE, upd_theta_opts = TRUE, num_threads = 1L) {
    .Call(`_spiox_spiox_wishart`, Y, X, coords, custom_dag, theta_opts, Sigma_start, mvreg_B_start, mcmc, print_every, sample_iwish, sample_mvr, sample_theta_gibbs, upd_theta_opts, num_threads)
}

spiox_latent <- function(Y, X, coords, custom_dag, theta_opts, Sigma_start, mvreg_B_start, mcmc = 1000L, print_every = 100L, sample_iwish = TRUE, sample_mvr = TRUE, sample_theta_gibbs = TRUE, upd_theta_opts = TRUE, num_threads = 1L) {
    .Call(`_spiox_spiox_latent`, Y, X, coords, custom_dag, theta_opts, Sigma_start, mvreg_B_start, mcmc, print_every, sample_iwish, sample_mvr, sample_theta_gibbs, upd_theta_opts, num_threads)
}

spiox_predict <- function(X_new, coords_new, Y, X, coords, dag, B, S, theta, num_threads = 1L) {
    .Call(`_spiox_spiox_predict`, X_new, coords_new, Y, X, coords, dag, B, S, theta, num_threads)
}

